version: '3.8'
services:
  # backend:
  #   image: geisonbiazus/markdown_notes_backend:alpha
  #   environment:
  #     DB_HOST: postgres
  #   ports:
  #     - 4000:4000
  # frontend:
  #   image: geisonbiazus/markdown_notes_frontend:alpha
  #   environment:
  #     REACT_APP_API_URL: http://localhost:4000
  #     REACT_APP_APP_ENV: production
  #   ports:
  #     - 3000:3000
  swagger:
    image: swaggerapi/swagger-ui:v3.38.0
    ports:
      - 4001:8080
    volumes:
      - ./docs:/docs
    environment:
      SWAGGER_JSON: /docs/openAPI.yml
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: markdown_notes
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  postgres_test:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: markdown_notes_test
    ports:
      - 5435:5432
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  postgres-test-data:
