version: '3.8'
services:
  # backend:
  #   image: geisonbiazus/markdown_notes:alpha
  #   environment:
  #     DB_HOST: postgres
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: markdown_notes
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  postgres_test:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: markdown_notes_test
    ports:
      - 5433:5432
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  postgres-test-data:
