apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - port: 80
      nodePort: 30002
      targetPort: api
      protocol: TCP
  selector:
    app: backend
  type: NodePort
