apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-rules
spec:
  rules:
    - host: api.notes.geisonbiazus.com
      http:
        paths:
          - path: /
            backend:
              serviceName: backend-service
              servicePort: 80
