openapi: '3.0.3'
info:
  version: '1.0.0'
  title: 'MarkdownNotes API'
  contact:
    name: 'Geison Biazus'
    email: 'geisonbiazus@gmail.com'

servers:
  - url: http://localhost:4000
    description: Local server
  - url: https://api.notes.geisonbiazus.com
    description: Production server

components:
  schemas:
  securitySchemes:
    bearerAuth:
      type: 'http'
      scheme: 'bearer'
      bearerFormat: 'JWT'

paths:
  '/pets':
    get:
      tags:
        - Pets
      description: 'Returns all pets from the system that the user has access to'
      operationId: 'getPets'
      security:
        - bearerAuth: []
      responses:
        200:
          description: 'A list of pets.'
          content:
            'application/json':
              schema:
                type: 'array'
                items:
                  pet_name:
                    type: 'string'
                    description: 'Pet Name'
                  pet_age:
                    type: 'string'
                    description: 'Pet Age'
