version: '3.8'
services:
  backend:
    image: geisonbiazus/markdown-notes-backend:33
    restart: always
    env_file: .env
    environment:
      DB_HOST: postgres
      VIRTUAL_HOST: api.notes.geisonbiazus.com
      LETSENCRYPT_HOST: api.notes.geisonbiazus.com
      DB_USERNAME: main
      DB_NAME: markdown_notes
    ports:
      - 4000:4000
  frontend:
    image: geisonbiazus/markdown-notes-frontend:40
    restart: always
    environment:
      REACT_APP_API_URL: https://api.notes.geisonbiazus.com
      REACT_APP_APP_ENV: production
      VIRTUAL_HOST: notes.geisonbiazus.com
      LETSENCRYPT_HOST: notes.geisonbiazus.com
    ports:
      - 3000:3000
  postgres:
    image: postgres:12
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: markdown_notes
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
