version: '3.8'
services:
  backend:
    image: geisonbiazus/markdown-notes-backend:66
    restart: always
    env_file: .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      VIRTUAL_HOST: api.notes.geisonbiazus.com
      LETSENCRYPT_HOST: api.notes.geisonbiazus.com
      DB_USERNAME: main
      DB_NAME: markdown_notes
      DEFAULT_EMAIL_SENDER: noreply@geisonbiazus.com
      FRONTEND_APP_URL: https://notes.geisonbiazus.com
      SENDGRID_USER_ACTIVATION_TEMPLATE_ID: d-fcf78bb3f0814e59a4bfd6dbb64804ab
    ports:
      - 4000:4000
  frontend:
    image: geisonbiazus/markdown-notes-frontend:68
    restart: always
    environment:
      REACT_APP_API_URL: https://api.notes.geisonbiazus.com
      REACT_APP_APP_ENV: production
      VIRTUAL_HOST: notes.geisonbiazus.com
      LETSENCRYPT_HOST: notes.geisonbiazus.com
    ports:
      - 3000:3000
  swagger:
    image: swaggerapi/swagger-ui:v3.38.0
    restart: always
    ports:
      - 4001:8080
    environment:
      URL: https://api.notes.geisonbiazus.com/public/open_api.yml
      VIRTUAL_HOST: api-docs.notes.geisonbiazus.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: api-docs.notes.geisonbiazus.com
  postgres:
    image: postgres:12
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: markdown_notes
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    restart: always
    env_file: .env
    environment:
      RABBITMQ_NODENAME: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "./volumes/rabbitmq-data:/var/lib/rabbitmq/mnesia"