name: Backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: node:14.5.0-alpine

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: markdown_notes_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: rabbitmq:3.8
        ports:
          - 5672:5672

    env:
      DB_TEST_URL: postgres://postgres:postgres@postgres:5432/markdown_notes_test
      RABBITMQ_URL: amqp://rabbitmq

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: Migrate DB
        run: npm run db:migrate:test

      - name: Run tests
        run: npm run test:ci

  build_and_push_image:
    name: Build and push Docker image
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            geisonbiazus/markdown-notes-backend:latest
            geisonbiazus/markdown-notes-backend:${{ github.run_number }}
