name: Frontend

on:
  push:
    branches:
  #     - master
  #   paths:
  #     - 'frontend/**'
  # pull_request:
  #   paths:
  #     - 'frontend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    if: false
    container: node:14.5.0-alpine

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build_and_push_image:
    name: Build and push Docker image
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            geisonbiazus/markdown_notes_backend:latest
            geisonbiazus/markdown_notes_backend:${{ github.run_number }}
  update_docker_compose:
    name: Update docker-compose
    # needs: build_and_push_image
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2

      - name: Update docker-compo file
        run: cat deploy/docker-compose/app.yml | deploy/bin/update_yaml services frontend image geisonbiazus/markdown_notes_frontend:${{ github.run_number }} > deploy/docker-compose/app.yml

      - name: Commit changes
        run: |
          echo "${{ github.ref }}"
          git config --global user.name 'Geison Biazus'
          git config --global user.email 'geisonbiazus@gmail.com'
          git commit -am "Update frontend version to ${{ github.run_number }}"
          git push
