name: Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - .github/workflows/frontend.yml
  pull_request:
    paths:
      - 'frontend/**'
      - .github/workflows/frontend.yml

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    container: node:14.5.0-alpine

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to heroku
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "notes-geisonbiazus" 
          heroku_email: "geisonbiazus@gmail.com"
          usedocker: true
          appdir: frontend
