name: Frontend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14.5.0-alpine

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
