name: Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    container: node:14.5.0-alpine

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build_and_push_image:
    name: Build and push Docker image
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            geisonbiazus/markdown-notes-frontend:latest
            geisonbiazus/markdown-notes-frontend:${{ github.run_number }}
